networks:
  homelab-network:
    external: true

services:
  agent:
    build:
      context: ./app
    container_name: homelab-agent
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DOCKER_HOST: tcp://homelab-socket-proxy:2375
    ports:
      - "8001:8001"
    networks:
      - homelab-network
    mem_limit: 1g
    volumes:
      - ./app:/app
